# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/Avnet/hdl/Projects/embv_p1300c/embv_python1300.xdc

# Block Designs: bd/embv_p1300c/embv_p1300c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c || ORIG_REF_NAME==embv_p1300c}]

# IP: bd/embv_p1300c/ip/embv_p1300c_processing_system7_0_0/embv_p1300c_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_processing_system7_0_0 || ORIG_REF_NAME==embv_p1300c_processing_system7_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_v_cfa_0_0/embv_p1300c_v_cfa_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_v_cfa_0_0 || ORIG_REF_NAME==embv_p1300c_v_cfa_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_v_cresample_0_0/embv_p1300c_v_cresample_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_v_cresample_0_0 || ORIG_REF_NAME==embv_p1300c_v_cresample_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_v_osd_0_0/embv_p1300c_v_osd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_v_osd_0_0 || ORIG_REF_NAME==embv_p1300c_v_osd_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_v_rgb2ycrcb_0_0/embv_p1300c_v_rgb2ycrcb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==embv_p1300c_v_rgb2ycrcb_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_v_tc_0_0/embv_p1300c_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_v_tc_0_0 || ORIG_REF_NAME==embv_p1300c_v_tc_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_v_tpg_0_0/embv_p1300c_v_tpg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_v_tpg_0_0 || ORIG_REF_NAME==embv_p1300c_v_tpg_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_avnet_hdmi_out_0_0/embv_p1300c_avnet_hdmi_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_avnet_hdmi_out_0_0 || ORIG_REF_NAME==embv_p1300c_avnet_hdmi_out_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_axi_mem_intercon_0/embv_p1300c_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_axi_mem_intercon_0 || ORIG_REF_NAME==embv_p1300c_axi_mem_intercon_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_xbar_0/embv_p1300c_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_xbar_0 || ORIG_REF_NAME==embv_p1300c_xbar_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_axi_vdma_0_0/embv_p1300c_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_axi_vdma_0_0 || ORIG_REF_NAME==embv_p1300c_axi_vdma_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_axi_vdma_1_0/embv_p1300c_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_axi_vdma_1_0 || ORIG_REF_NAME==embv_p1300c_axi_vdma_1_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_axis_tdata_subset_0/embv_p1300c_axis_tdata_subset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_axis_tdata_subset_0 || ORIG_REF_NAME==embv_p1300c_axis_tdata_subset_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_clk_wiz_0_0/embv_p1300c_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_clk_wiz_0_0 || ORIG_REF_NAME==embv_p1300c_clk_wiz_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_onsemi_python_cam_0_0/embv_p1300c_onsemi_python_cam_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_onsemi_python_cam_0_0 || ORIG_REF_NAME==embv_p1300c_onsemi_python_cam_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_onsemi_python_spi_0_0/embv_p1300c_onsemi_python_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_onsemi_python_spi_0_0 || ORIG_REF_NAME==embv_p1300c_onsemi_python_spi_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_processing_system7_0_axi_periph_0/embv_p1300c_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==embv_p1300c_processing_system7_0_axi_periph_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_xbar_1/embv_p1300c_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_xbar_1 || ORIG_REF_NAME==embv_p1300c_xbar_1}]

# IP: bd/embv_p1300c/ip/embv_p1300c_rst_processing_system7_0_108M_0/embv_p1300c_rst_processing_system7_0_108M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_rst_processing_system7_0_108M_0 || ORIG_REF_NAME==embv_p1300c_rst_processing_system7_0_108M_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_rst_processing_system7_0_149M_0/embv_p1300c_rst_processing_system7_0_149M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_rst_processing_system7_0_149M_0 || ORIG_REF_NAME==embv_p1300c_rst_processing_system7_0_149M_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_rst_processing_system7_0_76M_0/embv_p1300c_rst_processing_system7_0_76M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_rst_processing_system7_0_76M_0 || ORIG_REF_NAME==embv_p1300c_rst_processing_system7_0_76M_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_v_axi4s_vid_out_0_0/embv_p1300c_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==embv_p1300c_v_axi4s_vid_out_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_v_vid_in_axi4s_0_0/embv_p1300c_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==embv_p1300c_v_vid_in_axi4s_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_xlconstant_0_0/embv_p1300c_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_xlconstant_0_0 || ORIG_REF_NAME==embv_p1300c_xlconstant_0_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_xlconstant_1_0/embv_p1300c_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_xlconstant_1_0 || ORIG_REF_NAME==embv_p1300c_xlconstant_1_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_auto_pc_0/embv_p1300c_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_auto_pc_0 || ORIG_REF_NAME==embv_p1300c_auto_pc_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_auto_cc_0/embv_p1300c_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_auto_cc_0 || ORIG_REF_NAME==embv_p1300c_auto_cc_0}]

# IP: bd/embv_p1300c/ip/embv_p1300c_auto_pc_1/embv_p1300c_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_auto_pc_1 || ORIG_REF_NAME==embv_p1300c_auto_pc_1}]

# XDC: bd/embv_p1300c/ip/embv_p1300c_processing_system7_0_0/embv_p1300c_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_processing_system7_0_0 || ORIG_REF_NAME==embv_p1300c_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_cfa_0_0/embv_p1300c_v_cfa_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_v_cfa_0_0 || ORIG_REF_NAME==embv_p1300c_v_cfa_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_cfa_0_0/embv_p1300c_v_cfa_0_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_cresample_0_0/embv_p1300c_v_cresample_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_v_cresample_0_0 || ORIG_REF_NAME==embv_p1300c_v_cresample_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_cresample_0_0/embv_p1300c_v_cresample_0_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_osd_0_0/embv_p1300c_v_osd_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_v_osd_0_0 || ORIG_REF_NAME==embv_p1300c_v_osd_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_osd_0_0/embv_p1300c_v_osd_0_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_rgb2ycrcb_0_0/embv_p1300c_v_rgb2ycrcb_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==embv_p1300c_v_rgb2ycrcb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_rgb2ycrcb_0_0/embv_p1300c_v_rgb2ycrcb_0_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_tc_0_0/embv_p1300c_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_v_tc_0_0 || ORIG_REF_NAME==embv_p1300c_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_tc_0_0/embv_p1300c_v_tc_0_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_tpg_0_0/embv_p1300c_v_tpg_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_v_tpg_0_0 || ORIG_REF_NAME==embv_p1300c_v_tpg_0_0}] {/inst }]/inst ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_tpg_0_0/embv_p1300c_v_tpg_0_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_xbar_0/embv_p1300c_xbar_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_axi_vdma_0_0/embv_p1300c_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_axi_vdma_0_0 || ORIG_REF_NAME==embv_p1300c_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_axi_vdma_0_0/embv_p1300c_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_axi_vdma_0_0 || ORIG_REF_NAME==embv_p1300c_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_axi_vdma_0_0/embv_p1300c_axi_vdma_0_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_axi_vdma_1_0/embv_p1300c_axi_vdma_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_axi_vdma_1_0 || ORIG_REF_NAME==embv_p1300c_axi_vdma_1_0}] {/U0 }]/U0 ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_axi_vdma_1_0/embv_p1300c_axi_vdma_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_axi_vdma_1_0 || ORIG_REF_NAME==embv_p1300c_axi_vdma_1_0}] {/U0 }]/U0 ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_axi_vdma_1_0/embv_p1300c_axi_vdma_1_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_axis_tdata_subset_0/embv_p1300c_axis_tdata_subset_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_clk_wiz_0_0/embv_p1300c_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_clk_wiz_0_0 || ORIG_REF_NAME==embv_p1300c_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_clk_wiz_0_0/embv_p1300c_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_clk_wiz_0_0 || ORIG_REF_NAME==embv_p1300c_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_clk_wiz_0_0/embv_p1300c_clk_wiz_0_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_xbar_1/embv_p1300c_xbar_1_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_rst_processing_system7_0_108M_0/embv_p1300c_rst_processing_system7_0_108M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_rst_processing_system7_0_108M_0 || ORIG_REF_NAME==embv_p1300c_rst_processing_system7_0_108M_0}]

# XDC: bd/embv_p1300c/ip/embv_p1300c_rst_processing_system7_0_108M_0/embv_p1300c_rst_processing_system7_0_108M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_rst_processing_system7_0_108M_0 || ORIG_REF_NAME==embv_p1300c_rst_processing_system7_0_108M_0}]

# XDC: bd/embv_p1300c/ip/embv_p1300c_rst_processing_system7_0_108M_0/embv_p1300c_rst_processing_system7_0_108M_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_rst_processing_system7_0_149M_0/embv_p1300c_rst_processing_system7_0_149M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_rst_processing_system7_0_149M_0 || ORIG_REF_NAME==embv_p1300c_rst_processing_system7_0_149M_0}]

# XDC: bd/embv_p1300c/ip/embv_p1300c_rst_processing_system7_0_149M_0/embv_p1300c_rst_processing_system7_0_149M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_rst_processing_system7_0_149M_0 || ORIG_REF_NAME==embv_p1300c_rst_processing_system7_0_149M_0}]

# XDC: bd/embv_p1300c/ip/embv_p1300c_rst_processing_system7_0_149M_0/embv_p1300c_rst_processing_system7_0_149M_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_rst_processing_system7_0_76M_0/embv_p1300c_rst_processing_system7_0_76M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_rst_processing_system7_0_76M_0 || ORIG_REF_NAME==embv_p1300c_rst_processing_system7_0_76M_0}]

# XDC: bd/embv_p1300c/ip/embv_p1300c_rst_processing_system7_0_76M_0/embv_p1300c_rst_processing_system7_0_76M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embv_p1300c_rst_processing_system7_0_76M_0 || ORIG_REF_NAME==embv_p1300c_rst_processing_system7_0_76M_0}]

# XDC: bd/embv_p1300c/ip/embv_p1300c_rst_processing_system7_0_76M_0/embv_p1300c_rst_processing_system7_0_76M_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_axi4s_vid_out_0_0/embv_p1300c_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==embv_p1300c_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_axi4s_vid_out_0_0/embv_p1300c_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_vid_in_axi4s_0_0/embv_p1300c_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==embv_p1300c_v_vid_in_axi4s_0_0}] {/inst }]/inst ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_v_vid_in_axi4s_0_0/embv_p1300c_v_vid_in_axi4s_0_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_auto_pc_0/embv_p1300c_auto_pc_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_auto_cc_0/embv_p1300c_auto_cc_0_ooc.xdc

# XDC: bd/embv_p1300c/ip/embv_p1300c_auto_cc_0/embv_p1300c_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embv_p1300c_auto_cc_0 || ORIG_REF_NAME==embv_p1300c_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/embv_p1300c/ip/embv_p1300c_auto_pc_1/embv_p1300c_auto_pc_1_ooc.xdc

# XDC: bd/embv_p1300c/embv_p1300c_ooc.xdc
