// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module embv_p1300c_v_tpg_0_0_v_tpg_MultiPixStream2AXIvideo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        strmPix_V_val_0_V_dout,
        strmPix_V_val_0_V_empty_n,
        strmPix_V_val_0_V_read,
        strmPix_V_val_1_V_dout,
        strmPix_V_val_1_V_empty_n,
        strmPix_V_val_1_V_read,
        strmPix_V_val_2_V_dout,
        strmPix_V_val_2_V_empty_n,
        strmPix_V_val_2_V_read,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        Height,
        WidthOut,
        colorFormat
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 6'b1;
parameter    ap_ST_st2_fsm_1 = 6'b10;
parameter    ap_ST_st3_fsm_2 = 6'b100;
parameter    ap_ST_st4_fsm_3 = 6'b1000;
parameter    ap_ST_st5_fsm_4 = 6'b10000;
parameter    ap_ST_pp0_stg0_fsm_5 = 6'b100000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv3_7 = 3'b111;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] strmPix_V_val_0_V_dout;
input   strmPix_V_val_0_V_empty_n;
output   strmPix_V_val_0_V_read;
input  [7:0] strmPix_V_val_1_V_dout;
input   strmPix_V_val_1_V_empty_n;
output   strmPix_V_val_1_V_read;
input  [7:0] strmPix_V_val_2_V_dout;
input   strmPix_V_val_2_V_empty_n;
output   strmPix_V_val_2_V_read;
output  [23:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [15:0] Height;
input  [15:0] WidthOut;
input  [7:0] colorFormat;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axis_video_TVALID;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm = 6'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_25;
wire   [3:0] mapComp_address0;
reg    mapComp_ce0;
wire   [1:0] mapComp_q0;
reg   [10:0] j_reg_232;
reg    ap_sig_bdd_70;
wire   [15:0] grp_v_tpg_reg_unsigned_short_s_fu_243_ap_return;
reg   [15:0] tmp_reg_498;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_82;
wire    grp_v_tpg_reg_unsigned_short_s_fu_243_ap_done;
wire    grp_v_tpg_reg_unsigned_short_s_fu_249_ap_done;
wire   [11:0] tmp_126_fu_255_p1;
reg   [11:0] tmp_126_reg_503;
wire   [4:0] tmp_27_fu_275_p2;
wire   [1:0] i_1_fu_287_p2;
reg   [1:0] i_1_reg_517;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_102;
wire   [0:0] exitcond1_fu_281_p2;
wire   [11:0] tmp_129_fu_307_p1;
reg   [11:0] tmp_129_reg_534;
wire   [11:0] tmp_109_fu_310_p2;
reg   [11:0] tmp_109_reg_539;
wire   [1:0] tmp_130_fu_315_p1;
reg   [1:0] tmp_130_reg_544;
wire   [1:0] tmp_131_fu_319_p1;
reg   [1:0] tmp_131_reg_549;
wire   [1:0] tmp_132_fu_323_p1;
reg   [1:0] tmp_132_reg_554;
wire   [3:0] map_2_V_1_fu_356_p3;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_129;
wire   [3:0] map_2_V_3_fu_372_p3;
wire   [3:0] map_2_V_5_fu_380_p3;
wire   [0:0] exitcond2_fu_392_p2;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_142;
wire   [10:0] i_2_fu_397_p2;
reg   [10:0] i_2_reg_578;
wire   [0:0] exitcond3_fu_407_p2;
reg   [0:0] exitcond3_reg_583;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_5;
reg    ap_sig_bdd_153;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
wire    strmPix_V_val_0_V0_status;
reg    ap_sig_bdd_161;
reg    ap_sig_ioackin_m_axis_video_TREADY;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
wire   [10:0] j_1_fu_412_p2;
wire   [0:0] axi_last_V_fu_418_p2;
reg   [0:0] axi_last_V_reg_592;
wire    grp_v_tpg_reg_unsigned_short_s_fu_243_ap_start;
wire    grp_v_tpg_reg_unsigned_short_s_fu_243_ap_idle;
wire    grp_v_tpg_reg_unsigned_short_s_fu_243_ap_ready;
wire   [15:0] grp_v_tpg_reg_unsigned_short_s_fu_243_in_r;
wire    grp_v_tpg_reg_unsigned_short_s_fu_249_ap_start;
wire    grp_v_tpg_reg_unsigned_short_s_fu_249_ap_idle;
wire    grp_v_tpg_reg_unsigned_short_s_fu_249_ap_ready;
wire   [15:0] grp_v_tpg_reg_unsigned_short_s_fu_249_in_r;
wire   [15:0] grp_v_tpg_reg_unsigned_short_s_fu_249_ap_return;
reg   [3:0] map_V_2_s_reg_173;
reg   [3:0] map_V_1_s_reg_185;
reg   [3:0] map_2_V_4_reg_197;
reg   [1:0] i_reg_209;
reg   [10:0] i1_reg_221;
reg    grp_v_tpg_reg_unsigned_short_s_fu_243_ap_start_ap_start_reg = 1'b0;
reg    grp_v_tpg_reg_unsigned_short_s_fu_249_ap_start_ap_start_reg = 1'b0;
wire  signed [63:0] tmp_28_cast_fu_302_p1;
reg    strmPix_V_val_0_V0_update;
reg   [0:0] tmp_user_V_fu_100;
reg    ap_reg_ioackin_m_axis_video_TREADY = 1'b0;
wire   [2:0] tmp_128_fu_263_p1;
wire   [4:0] p_shl_cast_fu_267_p3;
wire   [4:0] tmp_127_fu_259_p1;
wire   [4:0] tmp_112_cast_fu_293_p1;
wire   [4:0] tmp_28_fu_297_p2;
wire   [0:0] sel_tmp_fu_336_p2;
wire   [3:0] map_0_V_cast_fu_332_p1;
wire   [0:0] sel_tmp2_fu_350_p2;
wire   [3:0] map_2_V_fu_342_p3;
wire   [3:0] map_2_V_2_fu_364_p3;
wire   [11:0] i1_cast_fu_388_p1;
wire   [11:0] j_cast_fu_403_p1;
wire   [7:0] tmp_21_fu_461_p5;
wire   [7:0] tmp_20_fu_450_p5;
wire   [7:0] tmp_19_fu_439_p5;
reg   [5:0] ap_NS_fsm;


embv_p1300c_v_tpg_0_0_v_tpg_MultiPixStream2AXIvideo_mapComp #(
    .DataWidth( 2 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
mapComp_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( mapComp_address0 ),
    .ce0( mapComp_ce0 ),
    .q0( mapComp_q0 )
);

embv_p1300c_v_tpg_0_0_v_tpg_reg_unsigned_short_s grp_v_tpg_reg_unsigned_short_s_fu_243(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_v_tpg_reg_unsigned_short_s_fu_243_ap_start ),
    .ap_done( grp_v_tpg_reg_unsigned_short_s_fu_243_ap_done ),
    .ap_idle( grp_v_tpg_reg_unsigned_short_s_fu_243_ap_idle ),
    .ap_ready( grp_v_tpg_reg_unsigned_short_s_fu_243_ap_ready ),
    .in_r( grp_v_tpg_reg_unsigned_short_s_fu_243_in_r ),
    .ap_return( grp_v_tpg_reg_unsigned_short_s_fu_243_ap_return )
);

embv_p1300c_v_tpg_0_0_v_tpg_reg_unsigned_short_s grp_v_tpg_reg_unsigned_short_s_fu_249(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_v_tpg_reg_unsigned_short_s_fu_249_ap_start ),
    .ap_done( grp_v_tpg_reg_unsigned_short_s_fu_249_ap_done ),
    .ap_idle( grp_v_tpg_reg_unsigned_short_s_fu_249_ap_idle ),
    .ap_ready( grp_v_tpg_reg_unsigned_short_s_fu_249_ap_ready ),
    .in_r( grp_v_tpg_reg_unsigned_short_s_fu_249_in_r ),
    .ap_return( grp_v_tpg_reg_unsigned_short_s_fu_249_ap_return )
);

embv_p1300c_v_tpg_0_0_v_tpg_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
v_tpg_mux_3to1_sel2_8_1_U138(
    .din1( strmPix_V_val_0_V_dout ),
    .din2( strmPix_V_val_1_V_dout ),
    .din3( strmPix_V_val_2_V_dout ),
    .din4( tmp_130_reg_544 ),
    .dout( tmp_19_fu_439_p5 )
);

embv_p1300c_v_tpg_0_0_v_tpg_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
v_tpg_mux_3to1_sel2_8_1_U139(
    .din1( strmPix_V_val_0_V_dout ),
    .din2( strmPix_V_val_1_V_dout ),
    .din3( strmPix_V_val_2_V_dout ),
    .din4( tmp_131_reg_549 ),
    .dout( tmp_20_fu_450_p5 )
);

embv_p1300c_v_tpg_0_0_v_tpg_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
v_tpg_mux_3to1_sel2_8_1_U140(
    .din1( strmPix_V_val_0_V_dout ),
    .din2( strmPix_V_val_1_V_dout ),
    .din3( strmPix_V_val_2_V_dout ),
    .din4( tmp_132_reg_554 ),
    .dout( tmp_21_fu_461_p5 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_lv1_0 == exitcond2_fu_392_p2))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ioackin_m_axis_video_TREADY
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_m_axis_video_TREADY <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & (ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_161 | ((ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_0 == ap_sig_ioackin_m_axis_video_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
            ap_reg_ioackin_m_axis_video_TREADY <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & (ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_161 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_logic_1 == m_axis_video_TREADY))) begin
            ap_reg_ioackin_m_axis_video_TREADY <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_161 | ((ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_0 == ap_sig_ioackin_m_axis_video_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_lv1_0 == exitcond3_fu_407_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & (ap_const_lv1_0 == exitcond2_fu_392_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_161 | ((ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_0 == ap_sig_ioackin_m_axis_video_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == exitcond3_fu_407_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & (ap_const_lv1_0 == exitcond2_fu_392_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_161 | ((ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_0 == ap_sig_ioackin_m_axis_video_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_lv1_0 == exitcond3_fu_407_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_v_tpg_reg_unsigned_short_s_fu_243_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_v_tpg_reg_unsigned_short_s_fu_243_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_70)) begin
            grp_v_tpg_reg_unsigned_short_s_fu_243_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_v_tpg_reg_unsigned_short_s_fu_243_ap_ready)) begin
            grp_v_tpg_reg_unsigned_short_s_fu_243_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_v_tpg_reg_unsigned_short_s_fu_249_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_v_tpg_reg_unsigned_short_s_fu_249_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_70)) begin
            grp_v_tpg_reg_unsigned_short_s_fu_249_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_v_tpg_reg_unsigned_short_s_fu_249_ap_ready)) begin
            grp_v_tpg_reg_unsigned_short_s_fu_249_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_161 | ((ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_0 == ap_sig_ioackin_m_axis_video_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_lv1_0 == exitcond3_fu_407_p2))) begin
        i1_reg_221 <= i_2_reg_578;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(exitcond1_fu_281_p2 == ap_const_lv1_0))) begin
        i1_reg_221 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        i_reg_209 <= i_1_reg_517;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~((ap_const_logic_0 == grp_v_tpg_reg_unsigned_short_s_fu_243_ap_done) | (ap_const_logic_0 == grp_v_tpg_reg_unsigned_short_s_fu_249_ap_done)))) begin
        i_reg_209 <= ap_const_lv2_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & (ap_const_lv1_0 == exitcond2_fu_392_p2))) begin
        j_reg_232 <= ap_const_lv11_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_161 | ((ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_0 == ap_sig_ioackin_m_axis_video_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == exitcond3_fu_407_p2))) begin
        j_reg_232 <= j_1_fu_412_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & (ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_161 | ((ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_0 == ap_sig_ioackin_m_axis_video_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        tmp_user_V_fu_100 <= ap_const_lv1_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(exitcond1_fu_281_p2 == ap_const_lv1_0))) begin
        tmp_user_V_fu_100 <= ap_const_lv1_1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_161 | ((ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_0 == ap_sig_ioackin_m_axis_video_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_lv1_0 == exitcond3_fu_407_p2))) begin
        axi_last_V_reg_592 <= axi_last_V_fu_418_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_161 | ((ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_0 == ap_sig_ioackin_m_axis_video_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        exitcond3_reg_583 <= exitcond3_fu_407_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        i_1_reg_517 <= i_1_fu_287_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        i_2_reg_578 <= i_2_fu_397_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        map_2_V_4_reg_197 <= map_2_V_5_fu_380_p3;
        map_V_1_s_reg_185 <= map_2_V_3_fu_372_p3;
        map_V_2_s_reg_173 <= map_2_V_1_fu_356_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(exitcond1_fu_281_p2 == ap_const_lv1_0))) begin
        tmp_109_reg_539 <= tmp_109_fu_310_p2;
        tmp_129_reg_534 <= tmp_129_fu_307_p1;
        tmp_130_reg_544 <= tmp_130_fu_315_p1;
        tmp_131_reg_549 <= tmp_131_fu_319_p1;
        tmp_132_reg_554 <= tmp_132_fu_323_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~((ap_const_logic_0 == grp_v_tpg_reg_unsigned_short_s_fu_243_ap_done) | (ap_const_logic_0 == grp_v_tpg_reg_unsigned_short_s_fu_249_ap_done)))) begin
        tmp_126_reg_503 <= tmp_126_fu_255_p1;
        tmp_reg_498 <= grp_v_tpg_reg_unsigned_short_s_fu_243_ap_return;
    end
end

always @ (ap_done_reg or exitcond2_fu_392_p2 or ap_sig_cseq_ST_st5_fsm_4) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_lv1_0 == exitcond2_fu_392_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (exitcond2_fu_392_p2 or ap_sig_cseq_ST_st5_fsm_4) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_lv1_0 == exitcond2_fu_392_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_153) begin
    if (ap_sig_bdd_153) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_25) begin
    if (ap_sig_bdd_25) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_82) begin
    if (ap_sig_bdd_82) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_102) begin
    if (ap_sig_bdd_102) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_129) begin
    if (ap_sig_bdd_129) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_142) begin
    if (ap_sig_bdd_142) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

always @ (m_axis_video_TREADY or ap_reg_ioackin_m_axis_video_TREADY) begin
    if ((ap_const_logic_0 == ap_reg_ioackin_m_axis_video_TREADY)) begin
        ap_sig_ioackin_m_axis_video_TREADY = m_axis_video_TREADY;
    end else begin
        ap_sig_ioackin_m_axis_video_TREADY = ap_const_logic_1;
    end
end

always @ (exitcond3_reg_583 or ap_sig_cseq_ST_pp0_stg0_fsm_5 or ap_sig_bdd_161 or ap_reg_ppiten_pp0_it1 or ap_reg_ioackin_m_axis_video_TREADY) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & (ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_161 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_logic_0 == ap_reg_ioackin_m_axis_video_TREADY))) begin
        m_axis_video_TVALID = ap_const_logic_1;
    end else begin
        m_axis_video_TVALID = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st3_fsm_2) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mapComp_ce0 = ap_const_logic_1;
    end else begin
        mapComp_ce0 = ap_const_logic_0;
    end
end

always @ (exitcond3_reg_583 or ap_sig_cseq_ST_pp0_stg0_fsm_5 or ap_sig_bdd_161 or ap_sig_ioackin_m_axis_video_TREADY or ap_reg_ppiten_pp0_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & (ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_161 | ((ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_0 == ap_sig_ioackin_m_axis_video_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        strmPix_V_val_0_V0_update = ap_const_logic_1;
    end else begin
        strmPix_V_val_0_V0_update = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_70 or grp_v_tpg_reg_unsigned_short_s_fu_243_ap_done or grp_v_tpg_reg_unsigned_short_s_fu_249_ap_done or exitcond1_fu_281_p2 or exitcond2_fu_392_p2 or exitcond3_fu_407_p2 or exitcond3_reg_583 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_161 or ap_sig_ioackin_m_axis_video_TREADY or ap_reg_ppiten_pp0_it1) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_70) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~((ap_const_logic_0 == grp_v_tpg_reg_unsigned_short_s_fu_243_ap_done) | (ap_const_logic_0 == grp_v_tpg_reg_unsigned_short_s_fu_249_ap_done))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            if (~(exitcond1_fu_281_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st5_fsm_4 : 
        begin
            if (~(ap_const_lv1_0 == exitcond2_fu_392_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_5;
            end
        end
        ap_ST_pp0_stg0_fsm_5 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_161 | ((ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_0 == ap_sig_ioackin_m_axis_video_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_lv1_0 == exitcond3_fu_407_p2))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_5;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_161 | ((ap_const_lv1_0 == exitcond3_reg_583) & (ap_const_logic_0 == ap_sig_ioackin_m_axis_video_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(ap_const_lv1_0 == exitcond3_fu_407_p2))) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_5;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_CS_fsm) begin
    ap_sig_bdd_102 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_129 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_142 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_153 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (exitcond3_reg_583 or strmPix_V_val_0_V0_status) begin
    ap_sig_bdd_161 = ((strmPix_V_val_0_V0_status == ap_const_logic_0) & (ap_const_lv1_0 == exitcond3_reg_583));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_25 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_start or ap_done_reg) begin
    ap_sig_bdd_70 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_82 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

assign axi_last_V_fu_418_p2 = (j_cast_fu_403_p1 == tmp_109_reg_539? 1'b1: 1'b0);

assign exitcond1_fu_281_p2 = (i_reg_209 == ap_const_lv2_3? 1'b1: 1'b0);

assign exitcond2_fu_392_p2 = (i1_cast_fu_388_p1 == tmp_129_reg_534? 1'b1: 1'b0);

assign exitcond3_fu_407_p2 = (j_cast_fu_403_p1 == tmp_126_reg_503? 1'b1: 1'b0);

assign grp_v_tpg_reg_unsigned_short_s_fu_243_ap_start = grp_v_tpg_reg_unsigned_short_s_fu_243_ap_start_ap_start_reg;

assign grp_v_tpg_reg_unsigned_short_s_fu_243_in_r = Height;

assign grp_v_tpg_reg_unsigned_short_s_fu_249_ap_start = grp_v_tpg_reg_unsigned_short_s_fu_249_ap_start_ap_start_reg;

assign grp_v_tpg_reg_unsigned_short_s_fu_249_in_r = WidthOut;

assign i1_cast_fu_388_p1 = i1_reg_221;

assign i_1_fu_287_p2 = (i_reg_209 + ap_const_lv2_1);

assign i_2_fu_397_p2 = (i1_reg_221 + ap_const_lv11_1);

assign j_1_fu_412_p2 = (j_reg_232 + ap_const_lv11_1);

assign j_cast_fu_403_p1 = j_reg_232;

assign m_axis_video_TDATA = {{{tmp_21_fu_461_p5}, {tmp_20_fu_450_p5}}, {tmp_19_fu_439_p5}};

assign m_axis_video_TDEST = ap_const_lv1_0;

assign m_axis_video_TID = ap_const_lv1_0;

assign m_axis_video_TKEEP = ap_const_lv3_7;

assign m_axis_video_TLAST = axi_last_V_reg_592;

assign m_axis_video_TSTRB = ap_const_lv3_0;

assign m_axis_video_TUSER = tmp_user_V_fu_100;

assign mapComp_address0 = tmp_28_cast_fu_302_p1;

assign map_0_V_cast_fu_332_p1 = mapComp_q0;

assign map_2_V_1_fu_356_p3 = ((sel_tmp2_fu_350_p2[0:0] === 1'b1) ? map_V_2_s_reg_173 : map_2_V_fu_342_p3);

assign map_2_V_2_fu_364_p3 = ((sel_tmp_fu_336_p2[0:0] === 1'b1) ? map_0_V_cast_fu_332_p1 : map_V_1_s_reg_185);

assign map_2_V_3_fu_372_p3 = ((sel_tmp2_fu_350_p2[0:0] === 1'b1) ? map_V_1_s_reg_185 : map_2_V_2_fu_364_p3);

assign map_2_V_5_fu_380_p3 = ((sel_tmp2_fu_350_p2[0:0] === 1'b1) ? map_0_V_cast_fu_332_p1 : map_2_V_4_reg_197);

assign map_2_V_fu_342_p3 = ((sel_tmp_fu_336_p2[0:0] === 1'b1) ? map_V_2_s_reg_173 : map_0_V_cast_fu_332_p1);

assign p_shl_cast_fu_267_p3 = {{tmp_128_fu_263_p1}, {ap_const_lv2_0}};

assign sel_tmp2_fu_350_p2 = (i_reg_209 == ap_const_lv2_0? 1'b1: 1'b0);

assign sel_tmp_fu_336_p2 = (i_reg_209 == ap_const_lv2_1? 1'b1: 1'b0);

assign strmPix_V_val_0_V0_status = (strmPix_V_val_0_V_empty_n & strmPix_V_val_1_V_empty_n & strmPix_V_val_2_V_empty_n);

assign strmPix_V_val_0_V_read = strmPix_V_val_0_V0_update;

assign strmPix_V_val_1_V_read = strmPix_V_val_0_V0_update;

assign strmPix_V_val_2_V_read = strmPix_V_val_0_V0_update;

assign tmp_109_fu_310_p2 = ($signed(ap_const_lv12_FFF) + $signed(tmp_126_reg_503));

assign tmp_112_cast_fu_293_p1 = i_reg_209;

assign tmp_126_fu_255_p1 = grp_v_tpg_reg_unsigned_short_s_fu_249_ap_return[11:0];

assign tmp_127_fu_259_p1 = colorFormat[4:0];

assign tmp_128_fu_263_p1 = colorFormat[2:0];

assign tmp_129_fu_307_p1 = tmp_reg_498[11:0];

assign tmp_130_fu_315_p1 = map_2_V_4_reg_197[1:0];

assign tmp_131_fu_319_p1 = map_V_1_s_reg_185[1:0];

assign tmp_132_fu_323_p1 = map_V_2_s_reg_173[1:0];

assign tmp_27_fu_275_p2 = (p_shl_cast_fu_267_p3 - tmp_127_fu_259_p1);

assign tmp_28_cast_fu_302_p1 = $signed(tmp_28_fu_297_p2);

assign tmp_28_fu_297_p2 = (tmp_27_fu_275_p2 + tmp_112_cast_fu_293_p1);


endmodule //embv_p1300c_v_tpg_0_0_v_tpg_MultiPixStream2AXIvideo

